/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CultosRouteImport } from './routes/cultos'
import { Route as DoacoesRouteImport } from './routes/doacoes'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QueroFazerParteRouteImport } from './routes/quero-fazer-parte'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CultosRoute = CultosRouteImport.update({
  id: '/cultos',
  path: '/cultos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacoesRoute = DoacoesRouteImport.update({
  id: '/doacoes',
  path: '/doacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroFazerParteRoute = QueroFazerParteRouteImport.update({
  id: '/quero-fazer-parte',
  path: '/quero-fazer-parte',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/quero-fazer-parte': typeof QueroFazerParteRoute
  '/sobre': typeof SobreRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/quero-fazer-parte': typeof QueroFazerParteRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/cultos': typeof CultosRoute
  '/doacoes': typeof DoacoesRoute
  '/eventos': typeof EventosRoute
  '/login': typeof LoginRoute
  '/quero-fazer-parte': typeof QueroFazerParteRoute
  '/sobre': typeof SobreRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/eventos'
    | '/login'
    | '/quero-fazer-parte'
    | '/sobre'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/eventos'
    | '/login'
    | '/quero-fazer-parte'
    | '/sobre'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/contato'
    | '/cultos'
    | '/doacoes'
    | '/eventos'
    | '/login'
    | '/quero-fazer-parte'
    | '/sobre'
    | '/admin/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  CultosRoute: typeof CultosRoute
  DoacoesRoute: typeof DoacoesRoute
  EventosRoute: typeof EventosRoute
  LoginRoute: typeof LoginRoute
  QueroFazerParteRoute: typeof QueroFazerParteRoute
  SobreRoute: typeof SobreRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultos': {
      id: '/cultos'
      path: '/cultos'
      fullPath: '/cultos'
      preLoaderRoute: typeof CultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacoes': {
      id: '/doacoes'
      path: '/doacoes'
      fullPath: '/doacoes'
      preLoaderRoute: typeof DoacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero-fazer-parte': {
      id: '/quero-fazer-parte'
      path: '/quero-fazer-parte'
      fullPath: '/quero-fazer-parte'
      preLoaderRoute: typeof QueroFazerParteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  CultosRoute: CultosRoute,
  DoacoesRoute: DoacoesRoute,
  EventosRoute: EventosRoute,
  LoginRoute: LoginRoute,
  QueroFazerParteRoute: QueroFazerParteRoute,
  SobreRoute: SobreRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
